export const category = [
  {
    id: 0,
    title: "UI/UX design",
    desc: "Designs that suit your business",
    image: "/images/category/uiux.png",
    bgColor: "#395B64",
  },
  {
    id: 1,
    title: "Web Apps",
    desc: "With high performance and speed",
    image: "/images/category/web.png",
    bgColor: "#4C3575",
  },
  {
    id: 2,
    title: "Mobile Apps",
    desc: "Bring your ideas to execution",
    image: "/images/category/mobile.png",
    bgColor: "#0F3460",
  },

  {
    id: 3,
    title: "AI Images",
    desc: "Generate images are per your imagination",
    image: "/images/category/ai.png",
    bgColor: "#9C3D54",
  },
  {
    id: 4,
    title: "Music Generation",
    desc: "Got something in your mind, let's create it",
    image: "/images/category/music.png",
    bgColor: "#B85C38",
  },
  {
    id: 5,
    title: "Cloud Services",
    desc: "Got all the power of cloud for your app",
    image: "/images/category/cloud.png",
    bgColor: "#1B2430",
  },
  {
    id: 6,
    title: "Graphics Design",
    desc: "Make your brand look appealing and modern",
    image: "/images/category/graphics.png",
    bgColor: "#1E5128",
  },
  {
    id: 7,
    title: "Animations",
    desc: "Got bored of still images, try something moving",
    image: "/images/category/animation.png",
    bgColor: "#2E8A99",
  },
];

export const populars = [
  {
    id: 0,
    image: "/images/popular/person1.png",
    cat: "Web Apps",
    username: "Saige Fuentes",
    bgColor: "#f95959",
  },
  {
    id: 1,
    image: "/images/popular/person2.png",
    cat: "Mobile Apps",
    username: "Bowen Higgins",
    bgColor: "#66bfbf",
  },
  {
    id: 2,
    image: "/images/popular/person3.png",
    cat: "Cloud Services",
    username: "Leighton Kramer",
    bgColor: "#6643b5",
  },
  {
    id: 3,
    image: "/images/popular/person4.png",
    cat: "Graphics Design",
    username: "Kylan Gentry",
    bgColor: "#a2c11c",
  },
];

export const services = [
  {
    id: 0,
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    desc: "service desc",
    price: 112,
    star: 5,
    username: "john cena",
  },
  {
    id: 1,
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    desc: "service desc",
    price: 112,
    star: 5,
    username: "john cena",
  },
  {
    id: 2,
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    desc: "service desc",
    price: 112,
    star: 5,
    username: "john cena",
  },
  {
    id: 3,
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    desc: "service desc",
    price: 112,
    star: 5,
    username: "john cena",
  },
  {
    id: 4,
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    desc: "service desc",
    price: 112,
    star: 5,
    username: "john cena",
  },
  {
    id: 5,
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    desc: "service desc",
    price: 112,
    star: 5,
    username: "john cena",
  },
  {
    id: 6,
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    desc: "service desc",
    price: 112,
    star: 5,
    username: "john cena",
  },
  {
    id: 7,
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    desc: "service desc",
    price: 112,
    star: 5,
    username: "john cena",
  },
];
