export const category = [
  {
    id: 0,
    title: "UI/UX design",
    desc: "Designs that suit your business",
    image: "/images/category/uiux.png",
    bgColor: "#395B64",
  },
  {
    id: 1,
    title: "Web Apps",
    desc: "With high performance and speed",
    image: "/images/category/web.png",
    bgColor: "#4C3575",
  },
  {
    id: 2,
    title: "Mobile Apps",
    desc: "Bring your ideas to execution",
    image: "/images/category/mobile.png",
    bgColor: "#0F3460",
  },

  {
    id: 3,
    title: "AI Images",
    desc: "Generate images are per your imagination",
    image: "/images/category/ai.png",
    bgColor: "#9C3D54",
  },
  {
    id: 4,
    title: "Music Generation",
    desc: "Got something in your mind, let's create it",
    image: "/images/category/music.png",
    bgColor: "#B85C38",
  },
  {
    id: 5,
    title: "Cloud Services",
    desc: "Got all the power of cloud for your app",
    image: "/images/category/cloud.png",
    bgColor: "#1B2430",
  },
  {
    id: 6,
    title: "Graphics Design",
    desc: "Make your brand look appealing and modern",
    image: "/images/category/graphics.png",
    bgColor: "#1E5128",
  },
  {
    id: 7,
    title: "Animations",
    desc: "Got bored of still images, try something moving",
    image: "/images/category/animation.png",
    bgColor: "#2E8A99",
  },
];

export const projects = [
  {
    id: 0,
    image: "/images/projects/web.jpg",
    pp: "/images/projects/person1.jpg",
    cat: "Web Apps",
    username: "Saige Fuentes",
  },
  {
    id: 1,
    image: "/images/projects/mobile.jpg",
    pp: "/images/projects/person2.jpg",
    cat: "Mobile Apps",
    username: "Bowen Higgins",
  },
  {
    id: 2,
    image: "/images/projects/cloud.jpg",
    pp: "/images/projects/person3.jpg",
    cat: "Cloud Services",
    username: "Leighton Kramer",
  },
  {
    id: 3,
    image: "/images/projects/graphics.jpg",
    pp: "/images/projects/person4.jpg",
    cat: "Graphics Design",
    username: "Kylan Gentry",
  },
  {
    id: 4,
    image: "/images/projects/animations.jpg",
    pp: "/images/projects/person5.jpg",
    cat: "Animations",
    username: "Amelie Griffith",
  },
  {
    id: 5,
    image: "/images/projects/music.avif",
    pp: "/images/projects/person6.jpg",
    cat: "Music Generation",
    username: "Marceline Avila",
  },
  {
    id: 6,
    image: "/images/projects/ai.jpg",
    pp: "/images/projects/person7.jpg",
    cat: "AI Images",
    username: "Franklin Sierra",
  },
  {
    id: 7,
    image: "/images/projects/uiux.avif",
    pp: "/images/projects/person8.jpg",
    cat: "UI/UX design",
    username: "Jaylen Blackwel",
  },
];

export const gigs = [
  {
    id: 0,
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    desc: "gig desc",
    price: 112,
    star: 5,
    username: "john cena",
  },
  {
    id: 1,
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    desc: "gig desc",
    price: 112,
    star: 5,
    username: "john cena",
  },
  {
    id: 2,
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    desc: "gig desc",
    price: 112,
    star: 5,
    username: "john cena",
  },
  {
    id: 3,
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    desc: "gig desc",
    price: 112,
    star: 5,
    username: "john cena",
  },
  {
    id: 4,
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    desc: "gig desc",
    price: 112,
    star: 5,
    username: "john cena",
  },
  {
    id: 5,
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    desc: "gig desc",
    price: 112,
    star: 5,
    username: "john cena",
  },
  {
    id: 6,
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    desc: "gig desc",
    price: 112,
    star: 5,
    username: "john cena",
  },
  {
    id: 7,
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    desc: "gig desc",
    price: 112,
    star: 5,
    username: "john cena",
  },
];
